//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winterdom.BizTalk.CryptoPipeline.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Winterdom.BizTalk.CryptoPipeline.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the algorithm to use when encrypting/decrypting messages.
        /// </summary>
        internal static string AlgorithmDesc {
            get {
                return ResourceManager.GetString("AlgorithmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string ComponentVersion {
            get {
                return ResourceManager.GetString("ComponentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypts incoming messages using a symmetric algorithm.
        /// </summary>
        internal static string DecryptionComponentDesc {
            get {
                return ResourceManager.GetString("DecryptionComponentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric Decryption.
        /// </summary>
        internal static string DecryptionComponentName {
            get {
                return ResourceManager.GetString("DecryptionComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypts outgoing messages using a symmetric algorithm.
        /// </summary>
        internal static string EncryptionComponentDesc {
            get {
                return ResourceManager.GetString("EncryptionComponentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric Encryption.
        /// </summary>
        internal static string EncryptionComponentName {
            get {
                return ResourceManager.GetString("EncryptionComponentName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon KeysIcon {
            get {
                object obj = ResourceManager.GetObject("KeysIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the SSO Configuration Application where the Key and IV are stored.
        /// </summary>
        internal static string SsoConfigAppDesc {
            get {
                return ResourceManager.GetString("SsoConfigAppDesc", resourceCulture);
            }
        }
    }
}
